### ISSUE TITLE
Configuration and getting started ?

### ISSUE THREAD

**Issue by AiGreek** [Blueforcer/AWTRIX#9]
I downloaded and uploaded the script but I do not understand how it works. I can not find any configuration file to put the identifiers of my wifi network, and after upload, absolutely nothing happens on the matrix. Could we have some additional information on getting started?

**Comment by Blueforcer** [comment]
There will be a documentation somewhere in the future. But at the moment I have no time for that. There is also a heavy bug in the actual firmware wich I found today
